#!/usr/bin/env python3
"""Regenerate derived data for the portal.

Run by the weekly routine (and safe to run by hand). It:
  * sorts the database (newest first, then name) for stable diffs,
  * refreshes the `updated` timestamp,
  * writes data/stats.json (totals, per-facet and per-tag counts),
  * writes data/digest.json — the sites added in the last `NEW_WINDOW_DAYS`
    days, which is what "showcase new finds" draws from,
  * prepends a dated entry to FINDS.md when there are new finds,
  * writes feed.xml — an Atom feed of the most recent additions so people
    can subscribe to new finds,
  * refreshes the stats block in README.md between the marker comments.

Standard library only.
"""
from __future__ import annotations

import datetime as dt
import json
import pathlib
from collections import Counter
from xml.sax.saxutils import escape

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "sites.json"
STATS = ROOT / "data" / "stats.json"
DIGEST = ROOT / "data" / "digest.json"
FEED = ROOT / "feed.xml"
FINDS = ROOT / "FINDS.md"
README = ROOT / "README.md"

NEW_WINDOW_DAYS = 14  # how recent counts as a "new find" in the showcase
FEED_LIMIT = 25  # most recent additions to include in the Atom feed
SITE_URL = "https://crab182.github.io/dark_websites/"
README_START = "<!-- STATS:START -->"
README_END = "<!-- STATS:END -->"


def load() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


def sort_sites(sites: list[dict]) -> list[dict]:
    return sorted(sites, key=lambda s: (s.get("added", ""), s.get("name", "")), reverse=True)


def build_stats(doc: dict, today: dt.date) -> dict:
    sites = doc["sites"]
    facet_counts = Counter(f for s in sites for f in s.get("facets", []))
    tag_counts = Counter(t for s in sites for t in s.get("tags", []))
    cutoff = today - dt.timedelta(days=NEW_WINDOW_DAYS)

    def is_new(site: dict) -> bool:
        try:
            return dt.date.fromisoformat(site.get("added", "")) >= cutoff
        except ValueError:
            return False

    return {
        "generated": today.isoformat(),
        "total": len(sites),
        "new_window_days": NEW_WINDOW_DAYS,
        "new_count": sum(1 for s in sites if is_new(s)),
        "facets": {k: facet_counts.get(k, 0) for k in doc["facets"]},
        "tags": dict(sorted(tag_counts.items(), key=lambda kv: (-kv[1], kv[0]))),
    }


def build_digest(doc: dict, today: dt.date) -> dict:
    cutoff = today - dt.timedelta(days=NEW_WINDOW_DAYS)
    new = []
    for s in doc["sites"]:
        try:
            if dt.date.fromisoformat(s.get("added", "")) >= cutoff:
                new.append(s)
        except ValueError:
            continue
    new.sort(key=lambda s: s.get("added", ""), reverse=True)
    return {
        "generated": today.isoformat(),
        "window_days": NEW_WINDOW_DAYS,
        "sites": [
            {"name": s["name"], "url": s["url"], "added": s["added"],
             "facets": s["facets"], "description": s["description"]}
            for s in new
        ],
    }


FINDS_HEADER = (
    "# New finds log\n\n"
    "A running diary of sites added to the database, newest first. "
    "Regenerated by the weekly routine.\n\n"
)


def update_finds_log(digest: dict, today: dt.date) -> None:
    if not digest["sites"]:
        return
    section = f"## {today.isoformat()}\n\n"
    section += "\n".join(
        f"- [{s['name']}]({s['url']}) — {s['description']} "
        f"_({', '.join(s['facets'])})_"
        for s in digest["sites"]
    ) + "\n\n"

    # Body = everything after the fixed header. Newest section goes on top.
    if FINDS.exists():
        existing = FINDS.read_text(encoding="utf-8")
        if f"## {today.isoformat()}" in existing:
            return  # already logged today; don't duplicate
        body = existing[len(FINDS_HEADER):] if existing.startswith(FINDS_HEADER) else existing
    else:
        body = ""

    FINDS.write_text(FINDS_HEADER + section + body, encoding="utf-8")


def build_feed(doc: dict, today: dt.date) -> str:
    """An Atom feed of the most recent additions (newest first)."""
    recent = sort_sites(list(doc["sites"]))[:FEED_LIMIT]
    updated = f"{today.isoformat()}T00:00:00Z"
    parts = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<feed xmlns="http://www.w3.org/2005/Atom">',
        f"  <title>{escape(doc.get('title', 'dark_websites'))}</title>",
        f"  <subtitle>New finds from the dark_websites reference database.</subtitle>",
        f'  <link href="{SITE_URL}" rel="alternate"/>',
        f'  <link href="{SITE_URL}feed.xml" rel="self"/>',
        f"  <id>{SITE_URL}</id>",
        f"  <updated>{updated}</updated>",
    ]
    for s in recent:
        added = f"{s['added']}T00:00:00Z"
        facets = ", ".join(s["facets"])
        summary = f"{s['description']} ({facets})"
        parts += [
            "  <entry>",
            f"    <title>{escape(s['name'])}</title>",
            f'    <link href="{escape(s["url"])}" rel="alternate"/>',
            f"    <id>tag:dark_websites,{s['added'][:4]}:{escape(s['id'])}</id>",
            f"    <updated>{added}</updated>",
            f"    <published>{added}</published>",
            "".join(f"    <category term=\"{escape(f)}\"/>" for f in s["facets"]),
            f"    <summary>{escape(summary)}</summary>",
            "  </entry>",
        ]
    parts.append("</feed>")
    return "\n".join(p for p in parts if p) + "\n"


def update_readme(stats: dict) -> None:
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    if README_START not in text or README_END not in text:
        return
    facets = " · ".join(f"`{k}` {v}" for k, v in stats["facets"].items())
    block = (
        f"{README_START}\n"
        f"**{stats['total']} sites** indexed · "
        f"**{stats['new_count']} new** in the last {stats['new_window_days']} days · "
        f"updated {stats['generated']}\n\n"
        f"By facet: {facets}\n"
        f"{README_END}"
    )
    start = text.index(README_START)
    end = text.index(README_END) + len(README_END)
    README.write_text(text[:start] + block + text[end:], encoding="utf-8")


def main() -> int:
    today = dt.datetime.now(dt.timezone.utc).date()
    doc = load()
    doc["sites"] = sort_sites(doc["sites"])
    doc["updated"] = today.isoformat()
    DATA.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    stats = build_stats(doc, today)
    STATS.write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")

    digest = build_digest(doc, today)
    DIGEST.write_text(json.dumps(digest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    FEED.write_text(build_feed(doc, today), encoding="utf-8")

    update_finds_log(digest, today)
    update_readme(stats)

    print(
        f"Built: {stats['total']} sites, {stats['new_count']} new "
        f"(last {NEW_WINDOW_DAYS}d). Wrote stats.json, digest.json, feed.xml."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
